# Generated by Django 5.1.4 on 2025-01-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phonenumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
