# Generated by Django 5.1.4 on 2024-12-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='address',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='investor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
