# Generated by Django 5.1.4 on 2024-12-24 18:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_investor_address_investor_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN'),
        ),
    ]
