# Generated by Django 5.1.4 on 2024-12-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0003_alter_investor_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='phonenumber',
        ),
    ]
