# Generated by Django 5.1.4 on 2024-12-24 18:53

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0004_remove_investor_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
