# Generated by Django 5.1.4 on 2024-12-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0005_investor_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='investor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
