# Generated by Django 5.1.4 on 2024-12-24 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0006_remove_investor_phonenumber_investor_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('roi', models.PositiveIntegerField()),
                ('deposit_date', models.DateField(auto_now_add=True)),
                ('maturity_date', models.DateField()),
                ('contract', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('investor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investor')),
            ],
        ),
    ]
