# Generated by Django 5.1.4 on 2024-12-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0007_trips_investment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
