# Generated by Django 5.1.4 on 2024-12-24 21:17

import datetime
import django.db.models.deletion
import investor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0008_delete_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_no', models.AutoField(primary_key=True, serialize=False)),
                ('to_location', models.CharField(max_length=100)),
                ('from_location', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=investor.models.Trips.default_end_date)),
                ('investor_name_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investor')),
            ],
        ),
    ]
