# Generated by Django 5.1.4 on 2024-12-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0009_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=256)),
                ('brand', models.CharField(max_length=256)),
                ('asset_model', models.CharField(max_length=256)),
                ('investment_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investment')),
                ('investor_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investor')),
            ],
        ),
    ]
