# Generated by Django 5.1.4 on 2025-01-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0011_bankdetails_contactdetails_groupcompanies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcompanies',
            name='companies',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='signingauthorities',
            name='signers',
            field=models.JSONField(default=list),
        ),
    ]
