# Generated by Django 5.1.4 on 2025-01-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0012_alter_groupcompanies_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='user_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='investor',
            name='phonenumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
