# Generated by Django 5.1.4 on 2025-01-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0013_investor_user_type_alter_investor_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='user_type',
            new_name='userType',
        ),
    ]
