# Generated by Django 5.1.4 on 2025-01-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0015_remove_assets_investor_asset_assets_numberplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='investor_name_trip',
        ),
        migrations.AddField(
            model_name='trips',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investor.assets'),
        ),
    ]
